### ISSUE TITLE
Unable to Load shuttle after it is saved

### ISSUE THREAD

**Issue by daedaelus** [MrMikeNZ/Space-Shuttle#1]
I am unable to load the shuttle after i put it together and save it. When loaded only the one piece shuttle frame loads with no parts even after they where added and saved. The object can not be clicked on and it displays as the default "Untitled" tag as if you started a new project.

This has been replicated on a new fresh install of kerbal only with module manager, active texture management, hyperedit and mechjeb added. This has been replicated on my main install as-well so it is happening on both clean and unclean install.

I am unable to launch or further test until this is resolved.

**Comment by daedaelus** [comment]
before a new load
https://www.dropbox.com/s/oyox83s1bmn7e7t/beforeload.png?dl=0
https://www.dropbox.com/s/4jeanub4q20ocjj/beforeload2.png?dl=0

after load
https://www.dropbox.com/s/642w7koqbs8do6i/afterload.png?dl=0
https://www.dropbox.com/s/1suca290ntirai1/afterload2.png?dl=0

My setup
https://www.dropbox.com/s/7ltybxm90ti0icn/programfiles.png?dl=0
https://www.dropbox.com/s/8g33q8gvnpssm6w/kerbalmods.png?dl=0

**Comment by MrMikeNZ** [comment]
possible cause is cfg's (fixed) new landing gear

**Comment by MrMikeNZ** [comment]
suspect new nose gear fault.
