### ISSUE TITLE
APU efficency

### ISSUE THREAD

**Issue by daedaelus** [MrMikeNZ/Space-Shuttle#10]
The APU power did not exceed more than 40 hours in space. The earliest APU's lasted a minimum of 72 hours. Each shuttle had 3 cells (or more) based on the mission. No shuttle launched without at least 3 active cells.This would total 216 hours power generation in space. I would increase the xeno count by x3 or adjust the efficiency of the power generator.

**Comment by MrMikeNZ** [comment]
Sweet I didnt know that. Will adjust

**Comment by daedaelus** [comment]
Every mission would of course adjust what they needed but the "standard" was 3 cells that could be rotated out if need be. So i would average 216 hours just based on simple math and not to over complicate it.

**Comment by daedaelus** [comment]
Fixed in 1.7.1
