### ISSUE TITLE
SRB Seperation Issue

### ISSUE THREAD

**Issue by daedaelus** [MrMikeNZ/Space-Shuttle#12]
The SRB's separate incorrectly. One of them separates towards the orbiter and the other down towards the ET. This occasionally makes the SRB hit the orbiter on separation. This appears to be there is only one SRB decoupler and it is reversed on the other side of the ET causing it to launch towards the orbiter and not down towards the ET.

**Comment by MrMikeNZ** [comment]
Interesting.
is this the nose cone thruster or seperator?
Does this happen only on symmetry? 

Can you check the placement rotation is correct and if it happens in single placement mode?

**Comment by daedaelus** [comment]
It seems that if you have mirroring on when attaching the SRB Decouplers it works but putting them on one at a time does not allow the right side to properly attach. It is correctable with mirroring when attaching the decoupler but it took me a while to figure that out which may confuse others.

**Comment by MrMikeNZ** [comment]
There is code available to force symmetrywhen placing part. Should I add that?

**Comment by daedaelus** [comment]
Lets try it and ill see if that fixes the issue.

**Comment by MrMikeNZ** [comment]
basic attachment only now. no chance of failure...?
