### ISSUE TITLE
SRB Nose Cone not displaying

### ISSUE THREAD

**Issue by daedaelus** [MrMikeNZ/Space-Shuttle#2]
I am unable to locate the SRB nose cone clean and unclean install has left me stumped where to find it. It is not under NASA and i searched through all parts and still can not find it. Either it is not displaying or im blind :)

**Comment by daedaelus** [comment]
Unable to launch until i find it or it is added. I see it in the folder but it just is not showing up in-game

**Comment by MrMikeNZ** [comment]
cfg fixed
