### ISSUE TITLE
SRB Decouplers cant be mirrored/reversed

### ISSUE THREAD

**Issue by daedaelus** [MrMikeNZ/Space-Shuttle#3]
Only one SRB decoupler exists with 1 attachment point for the SRB and ET there needs to be an additional SRB attachment point mirrored or another one added.

See how the SRBs are reversed
https://www.dropbox.com/s/lkpkweshq02h88v/srb1.png?dl=0

The decoupler needs another attachment point or a 2nd one with the attachment ball on the proper side
https://www.dropbox.com/s/e2mg2vqej7q3ph8/srb2.png?dl=0

When i flip the decoupler over to reverse it i can not attach the SRB vertically facing the proper direction.
https://www.dropbox.com/s/k88fureaqzbe75a/srb3.png?dl=0

**Comment by MrMikeNZ** [comment]
the wrong booster is used here. this is the built in decoupler version. for those single decouplers you use the booster with decoupler type. it doesn't have the build on decouplers...

let me test and change

**Comment by MrMikeNZ** [comment]
one of the 2 boosters removed because it was not needed.
now can be doubled up and mirror attached
